<?php
/**
 * @package TE Override
 * @version 1.0
 */
/*
Plugin Name: F&B Menus
Plugin URI: https://bellaworksweb.com
Description: Food and Beverage Menu generators.
Author: Austin Crane
Version: 1.0
Author URI: https://bellaworksweb.com
*/

/**
 *   Bring in the Styles
 * 
*/
// remove random autogenerated p tags in shortcode
remove_filter('the_content', 'wpautop');
add_filter('the_content', 'wpautop', 12);

// loads the stylesheet
add_action('wp_enqueue_scripts', 'wwc_food_style');
function wwc_food_style() {
	wp_register_style( 'wwc-food-styles',  plugin_dir_url( __FILE__ ) . 'wwc-food-styles.css?v=1.2' );
    wp_enqueue_style( 'wwc-food-styles' );
}
/**
 *  
 *  Create the Menu Post Type
*/

add_action('init', 'fnb_custom_menus');
function fnb_custom_menus() 
{
	
	$labels = array(
	'name' => _x('F&B Menus', 'post type general name'),
    'singular_name' => _x('F&B Menu', 'post type singular name'),
    'add_new' => _x('Add New', 'F&B Menu'),
    'add_new_item' => __('Add New F&B Menu'),
    'edit_item' => __('Edit F&B Menu'),
    'new_item' => __('New F&B Menu'),
    'view_item' => __('View F&B Menu'),
    'search_items' => __('Search F&B Menu'),
    'not_found' =>  __('No F&B Menu found'),
    'not_found_in_trash' => __('No F&B Menu found in Trash'), 
    'parent_item_colon' => '',
    'menu_name' => 'F&B Menus'
    
  );
  $args = array(
	'labels' => $labels,
    'public' => true,
    'menu_icon' => 'dashicons-carrot',
    'publicly_queryable' => true,
    'show_ui' => true, 
    'show_in_menu' => true, 
    'query_var' => true,
    'rewrite' => true,
    'capability_type' => 'post',
    'has_archive' => false, 
    'hierarchical' => false, // 'false' acts like posts 'true' acts like pages
    'menu_position' => 20,
    'supports' => array('title','editor','custom-fields','thumbnail'),
	
  ); 
  register_post_type('food_menus',$args); // name used in query

  // If we ever need a print url without headers and footers
  
 //  $labels = array(
	// 'name' => _x('Print', 'post type general name'),
 //    'singular_name' => _x('Print', 'post type singular name'),
 //    'add_new' => _x('Add New', 'Print'),
 //    'add_new_item' => __('Add New F&B Menu'),
 //    'edit_item' => __('Edit Print'),
 //    'new_item' => __('New Print'),
 //    'view_item' => __('View Print'),
 //    'search_items' => __('Search Print'),
 //    'not_found' =>  __('No Print found'),
 //    'not_found_in_trash' => __('No Print found in Trash'), 
 //    'parent_item_colon' => '',
 //    'menu_name' => 'Print'
 //  );
 //  $args = array(
	// 'labels' => $labels,
 //    'public' => true,
 //    'publicly_queryable' => true,
 //    'show_ui' => true, 
 //    'show_in_menu' => true, 
 //    'query_var' => true,
 //    'rewrite' => true,
 //    'capability_type' => 'post',
 //    'has_archive' => false, 
 //    'hierarchical' => false, // 'false' acts like posts 'true' acts like pages
 //    'menu_position' => 20,
 //    'supports' => array('title','editor','custom-fields','thumbnail'),
	
 //  ); 
 //  register_post_type('print_menus',$args); // name used in query
} // close custom post type

/*
##############################################
	Custom Taxonomies Controls Food location and shortcode
*/
add_action( 'init', 'build_fnb_tax', 0 );
 
function build_fnb_tax() {
// cusotm tax
    register_taxonomy( 'fnb_location', 'food_menus',
	 array( 
		'hierarchical' => true, // true = acts like categories false = acts like tags
		'label' => 'F&B Location', 
		'query_var' => true, 
		'rewrite' => true ,
		'show_admin_column' => true,
		'public' => true,
		'rewrite' => array( 'slug' => 'food-beverage-location' ),
		'_builtin' => true
	) );
	// register_taxonomy( 'fnb_location', 'food_menus',
	//  array( 
	// 	'hierarchical' => true, // true = acts like categories false = acts like tags
	// 	'label' => 'Food Type', 
	// 	'query_var' => true, 
	// 	'rewrite' => true ,
	// 	'show_admin_column' => true,
	// 	'public' => true,
	// 	'rewrite' => array( 'slug' => 'food-type' ),
	// 	'_builtin' => true
	// ) );
	
} // End build taxonomies

/**
 *  Create shortcode for River's Edge
 * 
    
 */
// 
require_once plugin_dir_path( __FILE__ ) . 'shortcodes/menus.php';
// require_once plugin_dir_path( __FILE__ ) . 'includes/admin.php';

